# Use the official Python image as a base
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Flask and other dependencies
RUN pip install --no-cache-dir flask

# Expose port 8080 to the outside world
EXPOSE 8081

# Define environment variable
ENV FLASK_APP=app.py

# Run the Flask application when the container launches
CMD ["flask", "run", "--host=0.0.0.0", "--port=8081", "--debug"]